baseurl = "/"
languageCode = "en-us"
title = "ä¸€ä¸ªå‘å¾®çš„çˆ¬ç‹—ğŸ¶"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "çœ‹çœ‹"
    url = "https://github.com/kuzuojian?tab=repositories"
[[menu.main]]
    name = "åœ°å›¾"
    url = "https://github.com/kuzuojian/last/blob/master/content/post/2019-05-22-ç”»_files/figure-html/unnamed-chunk-1-1.png"
[[menu.main]]
    name = "çœ‹ä¸­å›½"
    url = "http://www.people.com.cn/"
[[menu.main]]
    name = "netlify"
    url = "https://app.netlify.com/teams/kuzuojian/sites"
[[menu.main]]
    name = "CNKI"
    url = "www.cnki.net/"
[[menu.main]]
    name = "csdn"
    url = "https://www.csdn.net/"
[[menu.main]]
    name = "çŸ¥ä¸–ç•Œ"
    url = "http://www.huanqiu.com/?agt=15438"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

